/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Console_TextAttribute */

#ifndef _Included_jni_Console_TextAttribute
#define _Included_jni_Console_TextAttribute
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
