/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Console_Foreground */

#ifndef _Included_jni_Console_Foreground
#define _Included_jni_Console_Foreground
#ifdef __cplusplus
extern "C" {
#endif
#undef jni_Console_Foreground_BLUE
#define jni_Console_Foreground_BLUE 1L
#undef jni_Console_Foreground_GREEN
#define jni_Console_Foreground_GREEN 2L
#undef jni_Console_Foreground_RED
#define jni_Console_Foreground_RED 4L
#undef jni_Console_Foreground_INTENSITY
#define jni_Console_Foreground_INTENSITY 8L
#ifdef __cplusplus
}
#endif
#endif
