/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Console_BufferInfo */

#ifndef _Included_jni_Console_BufferInfo
#define _Included_jni_Console_BufferInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
